name: sigbang
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Networking
  dio: ^5.3.2
  
  # Routing
  go_router: ^13.0.1
  
  # Authentication
  google_sign_in: ^6.2.1

  http: ^1.2.1
  
  # Media
  image_picker: ^1.0.7
  crop_your_image: ^1.1.0
  flutter_image_compress: ^2.2.0
  path_provider: ^2.1.3
  image: ^4.1.7
  wechat_assets_picker: ^9.2.1
  photo_manager: ^3.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/fonts/
    - assets/images/
    - .env.dev
    - .env.prod
